// Client-safe registry index.  Imports the prebuilt static JSON map (no
// Node `fs`/`path` dependencies — webpack can bundle this for the browser).
//
// The map is generated by `scripts/build-compound-config.ts` before
// `next build`.  Run `npm run build:registry-config` if you want to
// regenerate without a full Next.js build.

import generated from "./generated.json";
import type { CompoundChainConfig } from "./types";

const COMPOUND_DEPLOYMENTS = generated as unknown as Record<number, CompoundChainConfig>;

/** Look up the Compound deployment for a given chainId. Returns undefined if not deployed there. */
export function getCompoundConfig(chainId: number): CompoundChainConfig | undefined {
  return COMPOUND_DEPLOYMENTS[chainId];
}

/** All chains where Compound is currently deployed (non-retired). */
export function listCompoundChains(): CompoundChainConfig[] {
  return Object.values(COMPOUND_DEPLOYMENTS);
}

/** Get the registry-declared single-tx flows for a chain. */
export function getSingleTxFlows(chainId: number): string[] {
  return COMPOUND_DEPLOYMENTS[chainId]?.ux.singleTxFlows ?? [];
}

/** Get the registry-declared bundle flows. Empty when jito.enabled=false on this chain. */
export function getBundleFlows(chainId: number): string[] {
  const cfg = COMPOUND_DEPLOYMENTS[chainId];
  if (!cfg || !cfg.jitoEnabled) return [];
  return cfg.ux.bundleFlows;
}

export type { CompoundChainConfig, CompoundDeployment } from "./types";
export { buildCompoundChainConfig, buildCompoundChainConfigMap, resolveRpcRef } from "./loader";
